name: Java Workflow
on: workflow_dispatch
jobs: 
  maven_setup:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with: 
          java-version: "17"
          distribution: "oracle"
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - name: Upload a build artifact
        uses: actions/upload-artifact@4.6.0
        with: 
          name: Package_Java
          path: staging
       
       
  
